### PR TITLE
Adding card type 'Mir'

### PR DESCRIPTION
**Pull request by CooLSeS**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Could you provide some documentation around the Mir credit card type so we can verify that the regexes you've provided are accurate?

In addition, you'll need to fix the failing tests and add tests for the Mir card type.

**Comment by CooLSeS** [comment]
Information on credit card "mir" https://en.wikipedia.org/wiki/Payment_card_number
I had to fix it, because originally was different information from the bank.
And I corrected tests.

**Comment by crookedneighbor** [comment]
Do you have a link to documentation from the bank itself?

**Comment by CooLSeS** [comment]
What kind of documentation will be suitable? Can you give me some references there to search?
http://www.nspk.ru/en/ - site national payment cards system

**Comment by skunkworks** [comment]
@CooLSeS We are hoping to confirm with official documentation from Mir that the valid BIN range is 2200-2204, rather than relying on Wikipedia. We couldn't find anything via Google, so if you have a link it would be much appreciated.

**Comment by quinnjn** [comment]
@CooLSeS We would like official documentation from a bank that supports Mir before we can accept this PR. 

We're going to close this for now. Let us know when official documentation can be referenced.

**Comment by imdkva** [comment]
Hi!

I'm very interested in this pr. I can confirm that MIR range is 2200-2204, the trouble is there is no public source for this information. NPSC usually pushes this kind of documents directly to partners via email and i'm not sure it's not under NDA.

How can you refer other systems? For example, MasterCard developer support tell me i should register  to get bin tables: https://mastercarddevelopersupport.desk.com/customer/en/portal/topics/957220-bin-table

**Comment by crookedneighbor** [comment]
We need documentation. If it is not publicly available, you can have MIR send the documentation to support@braintreepayments.com and reference this pull request.

**Comment by vorobeez** [comment]
I'm looking forward for accepting this pr too.

**Comment by jehy** [comment]
MIR is already on wikipedia: https://en.wikipedia.org/wiki/Payment_card_number
First cards were issued in 2015 and now there are already millions of them.
You are forcing developers to make forks and this is very sad.

We can't have MIR send you documentation - it's like asking Microsoft to send Windows documentation to developer.

**Comment by crookedneighbor** [comment]
I do not think it is too much to ask for official documentation from MIR.

Braintree doesn't process MIR cards. So I am hesitant to include anything in this library that we cannot verify ourselves.

**Comment by crookedneighbor** [comment]
We got official documentation for the Mir card type, and this has been released as part of v6.3.0

**Pull request closed without merging**
