### PR TITLE
Adding RuPay Card

### PR DESCRIPTION
**Pull request by avinashjsap**
Added **RuPay** to Built-in card type as it is being popularly used in India

https://en.wikipedia.org/wiki/RuPay
https://en.wikipedia.org/wiki/Payment_card_number

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Do you have official documentation from RuPay?

**Comment by avinashjsap** [comment]
Hello Blade, I could not find the card numbers mentioned in the official documentation This is the official website -> RuPay Credit cards, Debit Cards & International Cards | NPCI And But from the Brand mark guidelines(RuPay Revised Guideline-4_30th July (npci.org.in)) we could guarantee that it starts with “60” and “65” Regards Avinash JeevaSent from Mail for Windows 10 From: Blade BarringerSent: Monday, June 14, 2021 5:41 PMTo: braintree/credit-card-typeCc: Avinash J; AuthorSubject: Re: [braintree/credit-card-type] Adding RuPay Card (#132) Do you have official documentation from RuPay?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by avinashjsap** [comment]
Do we have the official documentation for other cards?
If so could you please share them ?

**Comment by crookedneighbor** [comment]
We have documentation from the partners that Braintree works with for our own credit card processing, but we do not have documentation for card brands that Braintree does not directly support (and we don't have the bandwidth to chase it down from the card issuers on our own). 

I'm happy for this module to support cards that Braintree doesn't specifically process for, but we need to be careful that the card ranges are accurate, therefore, we need official documentation for the possible ranges.

If that's impossible, and you still want to include RuPay, our official recommendation is to use the methods that allows you to add/modify card types. https://github.com/braintree/credit-card-type#adding-card-types

**Comment by nishanthpappula** [comment]
Hi @avinashjsap @crookedneighbor, I am using this package in my project for fetching and validating the card details. I noticed that it doesn't work for the Rupay card type.
I just saw that Pull Request has already been raised for Rupay integration. Is there any plan of merging this PR so that it can solve our Rupay related issues.

**Comment by avinashjsap** [comment]
@nishanthpappula , as @crookedneighbor  commented, You can create custom cards using the methods provided and feel free to use the Rupay Card regex.

**Comment by Abhishek0067** [comment]
RuPay card BIN numbers starting with 60, 652, 81, 82, 508, 3538, 3561.

you can see RuPay BIN numbers here - https://www.desidime.com/deals/bookmyshow-flat-75-off-on-payment-above-100-using-rupay-platinum-debit-card-flat-250-off-on-250-using-rupay-credit-card-flat-500-off-on-500-using-rupay-select-card

**Comment by nishanthpappula** [comment]
@avinashjsap @Abhishek0067 
Thanks for the quick response. It's working with the approach suggested.

**Comment by Abhishek0067** [comment]
> RuPay card BIN numbers starting with 60, 652, 653, 654, 81, 82, 508, 3538, 3561.
> 
> you can see RuPay BIN numbers here - https://www.desidime.com/deals/bookmyshow-flat-75-off-on-payment-above-100-using-rupay-platinum-debit-card-flat-250-off-on-250-using-rupay-credit-card-flat-500-off-on-500-using-rupay-select-card

Just an update RuPay card BIN number now also start with 653. In future also RuPay will start BIN number 654.

**Pull request closed without merging**
