### PR TITLE
Adding the Visa Electron card type

### PR DESCRIPTION
**Pull request by mjhammond**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Can you provide documentation about the regexes you used?

**Comment by mjhammond** [comment]
I haven't been able to find any really concrete documentation for Electron prefixes yet, but I will keep looking.

**Comment by skunkworks** [comment]
We are closing this issue for now, but please bump this issue to let us know if you find any documentation.

**Comment by mapb1990** [comment]
http://stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html

Visa Electron | 4026, 417500, 4405, 4508, 4844, 4913, 4917

**Comment by crookedneighbor** [comment]
v6.2.0 allows you to add custom card brands. See https://github.com/braintree/credit-card-type#adding-card-types for documentation.

**Pull request closed without merging**
